export const alertedProductsTableData = [
  {
    id: "ALP-001",
    supplier: "Cooperativa Cauca",
    productId: "PRD-0001247",
    productName: "Fertilizante NPK 15-15-15",
    unitOfMeasure: "Saco x 50 kg",
    commercialBrand: "AgroForte",
    minimumPrice: 120000,
    maximumPrice: 128500,
    saleUnitValue: 128500,
    fairCatalogValue: 119800,
    alertCategory: "Sobreprecio",
    managementType: "Mesa técnica",
    alertManagement: "Asignada",
    hasAssignedManagementType: false,
  },
  {
    id: "ALP-002",
    supplier: "BioCampo Ltda.",
    productId: "PRD-0001123",
    productName: "Abono orgánico compost",
    unitOfMeasure: "Saco x 40 kg",
    commercialBrand: "BioCampo",
    minimumPrice: 18000,
    maximumPrice: 27000,
    saleUnitValue: 27000,
    fairCatalogValue: 25000,
    alertCategory: "Sin estudio",
    managementType: "Ajuste de precios",
    alertManagement: "En revisión",
    hasAssignedManagementType: false,
  },
  {
    id: "ALP-003",
    supplier: "Agroinsumos del Sur",
    productId: "PRD-001569",
    productName: "Semilla de plátano hartón",
    unitOfMeasure: "Unidad",
    commercialBrand: "AgroSur",
    minimumPrice: 1500,
    maximumPrice: 1750,
    saleUnitValue: 1750,
    fairCatalogValue: 1600,
    alertCategory: "Fuera de rango",
    managementType: "Validación",
    alertManagement: "Cerrada",
    hasAssignedManagementType: false,
  },
];
